insert into `Student` (`username`, `password`) values ('yulang.dev@gmail.com', '{bcrypt}$2b$10$pT3NOQThwzPeoh7fwlWEju2DMCYg5c2KqrGgjKl6tOuS37BwMSVvy');

INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is holding a pen in her right hand.','여자가 오른손에 펜을 들고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Glass bottles are arranged in rows.','유리병이 여러 줄로 정리되어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A ship is passing under the bridge.','배 한 척이 다리 밑을 지나가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is passing a book to a colleague.','여자가 동료에게 책을 건네주고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A customer is reaching for some merchandise.','손님이 상품을 향해 손을 뻗고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A band member is adjusting a microphone.','밴드 멤버가 마이크를 조정하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are pointing to chart on the wall.','사람들이 벽에 있는 차트를 가리키고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some people are loading suitcases into the bus.','몇몇 사람들이 버스에 여행용 가방을 싣고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The chairs are not occupied.','의자들이 비어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The chairs are unoccupied.','의자들이 비어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The chairs are empty.','의자들이 비어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('One of the men is bending over the luggage.','한 남자가 수하물 위로 몸을 굽히고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is leaning against the wall.','남자가 벽에 기대어 서 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is propped against the wall.','남자가 벽에 기대어 서 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The truck is parked in a garage.','트럭이 차고에 주차되어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some cars are parked in a garage.','차들이 차고에 주차되어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is throwing away some papers.','여자가 종이를 버리고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some people are packing their suitcases.','몇몇 사람들이 여행용 가방을 싸고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Buildings are overlooking the water.','건물들이 강 위로 솟아 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A passenger is walking down the aisle.','한 승객이 통로를 걸어가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is filling up a cup.','여자가 컵을 채우고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The shelves are filled with books.','선반들이 책으로 가득 차 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some women are inspecting the vehicle.','몇몇 여자들이 차량을 살펴보고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some workers are trimming bushes.','몇몇 일꾼들이 관목을 다듬고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The road through the forest has been paved.','숲을 지나는 길이 포장되어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Performers have assembled under a canopy.','공연자들이 차양 아래에 모여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The women are assembling a desk.','여자들이 책상을 조립하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some boats are sailing on the water.','배 몇 척이 항해하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A sail has been raised above a ship.','돛이 배 위로 올려져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is mowing the grass between the trees.','남자가 나무들 사이에 있는 잔디를 깎고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('One woman is copying a document.','한 여자가 서류를 복사하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('People are performing under a tent.','사람들이 텐트 아래에서 연주하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('People are lined up to watch a street performer.','사람들이 거리 공연가를 보기 위해 늘어서 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A ferry is transporting people across a river.','페리가 강을 가로질러 사람들을 실어 나르고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A woman is shopping in an outdoor market.','한 여자가 야외 시장에서 쇼핑하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A woman is pouring water into a cup.','한 여자가 컵에 물을 따르고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some tables are shaded by umbrellas.','몇몇 테이블에 파라솔에 의해 그늘이 져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('All of the tables are in the shade.','모든 테이블이 그늘에 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The woman is lowering a window shade.','여자가 창문의 블라인드를 내리고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The woman is surrounded by flowers.','여자가 꽃으로 둘러싸여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Flowers surround the woman.','여자가 꽃으로 둘러싸여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The sailboat is being towed throwugh the water.','돛단배가 물살을 가르며 예언되고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some of the spectators are wearing hats.','몇몇 관중은 모자를 쓰고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Leaves have been raked into piles.','나뭇잎들이 갈퀴로 긁어 모아 쌓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are placing books on a table.','사람들이 책을 탁자 위에 놓고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is putting on a jacket.','여자가 자켓을 입는 중이다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is trying on a jacket.','남자가 자켓을 입는 중이다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Boxes have been placed on the ground.','상자들이 바닥에 놓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Boxes have been put on the ground.','상자들이 바닥에 놓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Boxes have been set on the ground.','상자들이 바닥에 놓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Boxes have been positioned on the ground.','상자들이 바닥에 놓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are facing each other.','그들은 서로 마주 보고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Pieces of luggage are lined up on the pavement.','짐들이 포장도로 위에 늘어서 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is plugging in a machine.','여자가 기계를 전원에 연결하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Pedestrians are crossing the street.','보행자들이 길을 건너고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is standing with her arms crossed.','여자가 팔짱을 낀 채 서 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are hanging a picture on a wall.','사람들이 그림을 벽에 걸고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A mirror is hanging on the wall.','거울이 벽에 걸려 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The waiter is distributing plates of food.','종업원이 음식접시를 나누어 주고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The waiter is handing out plates of food.','종업원이 음식접시를 나누어 주고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is folding his jacket.','남자가 자킷을 접고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The bridge is reflected in the water.','다리가 물에 비치고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('One woman is looking at her reflection.','한 여자가 거울에 비친 자신의 모습을 보고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is addressing his colleagues.','남자가 동료들에게 연설을 하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Small tress have been planted in individual pots.','작은 나무들이 각각 화분에 심어져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The women are watering the plants.','여자들이 식물에 물을 주고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The man is filing some documents.','남자가 문서를 파일로 철하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is operating some factory machinery.','남자가 공장 기계를 작동하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is stacking up some bricks.','남자가 벽돌을 쌓고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is standing by two stacks of plates.','남자가 두 무더기의 접시들 옆에 서 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('An audience is clapping for some musicians.','청중이 연주가들에게 박수를 보내고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The woman is kneeling in the garden.','여자가 정원에서 무릎을 꿇고 앉아 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are turning on the lights.','사람들이 전등을 펴고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are turning off the lights.','사람들이 전등을 끄고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Pedestrians are strolling beside a riverbank.','보행자들이 강둑 옆을 거닐고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Dishes have been piled in a drying rack.','접시들이 건조대에 쌓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Dishes have been stacked in a drying rack.','접시들이 건조대에 쌓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some men are storing luggage above their seats.','남자들이 좌석 위에 짐을 보관하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is picking up his briefcase.','남자가 서류가방을 집어 들고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is picking up some flowers.','남자가 꽃을 꺾고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Waiters are serving beverages to the customers.','종업원들이 손님들에게 음료를 제공하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Passengers are boarding a bus.','승객들이 버스에 탑승하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some boards have been piled on a deck.','판자들이 갑판에 쌓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some people are getting on a bus.','몇몇 사람들이 버스에 오르고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is riding a bicycle.','남자가 자전거를 타고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is framing a piece of art.','여자가 미술 작품을 액자에 넣고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are relaxing on the lawn.','사람들이 잔디 위에서 쉬고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The carpet has been rolled up in the corner.','카펫이 구석에 둘둘 말려 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A shopper is rolling a cart down a walkway.','한 쇼핑객이 통로에서 카트를 굴리고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A performer is bowing before an audience.','공연자가 청중 앞에서 인사하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Tree branches are being cleared off a walkway.','나뭇가지들이 길에서 치워지고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The shoes are displayed on a shelf.','신발이 선반 위에 진열되어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A sculpture is on display outside.','조각상이 야외에 전시되어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A bridge extends towards a domed building.','다리가 돔 모양의 건물 쪽으로 뻗어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some vegetables are being cooked.','채소가 요리되고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A woman is shipping a cup of coffee.','여자가 커피 한 잔을 마시고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is working on the tire.','남자가 타이어를 손보고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('One of the men is sweeping an outdoor area.','한 남자가 야외 장소를 쓸고 이싿.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The woman is browsing through some magazines.','여자가 잡지들을 훑어보고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The bicycle is lying on the ground.','자전거가 땅에 뉘어져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is lying on the sofa.','여자가 소파 위에 누워 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is wrapping a book in paper.','남자가 종이로 책을 싸고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some people are exercising in a park.','사람들이 공원에서 운동하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A plaza is bordered by a fence.','광장에 울타리가 쳐져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A man is setting up a podium.','남자가 연단을 설치하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Towels have been spread out on the sand.','수건들이 모래 위에 펼쳐져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is wiping off a kitchen counter.','남자가 주방 조리대를 닦고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are dining at a restaurant.','사람들이 식당에서 식사하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The office is stocked with supplies.','사무실이 비품으로 채워져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Equipment is being fastened to the roof of a car.','차의 지붕에 장비가 매달려 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The men are exchanging business cards.','남자들이 명함을 주고받고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A woman is taking notes on a board.','여자가 칠판에 메모를 하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The silverware is being polished.','은식기들이 윤이 나게 닦여지고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A machine is lifting bags onto a shelf.','기계가 자루들을 들어 올려 선반에 얹고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A high wall runs alongside the train tracks.','높은 담이 기찻길과 나란히 이어져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A man is running up a ramp.','남자가 경사로를 달려 올라가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is sorting out some papers.','여자가 서류를 분류하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The women are sewing some clothing.','여자들이 옷을 바느질하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Vendors are putting away their displays.','판매자들이 진열품들을 치우고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The fountain is spraying water into the air.','분수가 공중에 물을 뿌리고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A woman is entering numbers on a keypad.','여자가 키패드로 숫자를 입력하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A group of people is entering the room.','한 무리의 사람들이 방에 들어가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are moving a piece of furniture.','사람들이 가구 한 점을 옴기고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The driver is checking the engine.','운전사가 엔진을 점검하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The man and woman are checking their luggage.','남자가 여자가 짐을 맡기고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A man is climbing some stairs.','한 남자가 계단을 올라가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The man is rowing a boat across the harbor.','남자가 배의 노를 저어 항구 너머로 가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The chairs have been arranged in rows.','의자가 여러 줄로 놓여 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A car is exiting a parking garage.','차 한대가 주차장에서 나가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A car is leaving a parking garage.','차 한대가 주차장에서 나가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some paintings have been mounted on the wall.','몇몇 그림들이 벽에 걸려 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some diners are seated across from each other.','몇몇 식사 손님들이 마주 보고 앉아 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some diners are sitting across from each other.','몇몇 식사 손님들이 마주 보고 앉아 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some boats are docked ata pier.','배 몇 척이 부두에 정박해 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A man is fishing from a dock.','한 남자가 부두에서 낚시를 하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A man is putting up a tent.','한 남자가 텐트를 치고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The man is putting up a sign.','남자가 안내판을 내걸고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some trees are casting shadows on a path.','나무 몇 그루가 길에 그림자를 드리우고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A stool has fallen over on the ground.','의자가 바닥에 넘어져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A tablecloth has fallen on the floor.','테이블보가 바닥에 떨어져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Signs are being posted at an intersection.','교차로에 표지판이 세워지고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('One of the men is taking off his jacket.','한 남자가 재킷을 벗고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('An aircraft is taking off from a runway.','비행기가 활주로에서 이륙하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Tables and chairs are set up outdoors.','테이블과 의자가 야외에 설치되어 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is filling a barrel with water.','남자가 통에 물을 채우고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The women are watering the plants.','여자들이 식물에 물을 주고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is printing a set of documents.','여자가 일련의 서류들을 인쇄하고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are setting the table for dinner.','사람들이 저녁식사를 위해 상을 차리고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is turning a key in a lock.','여자가 열쇠를 자물쇠에 넣어 돌리고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The lab technician is locking the door.','실험실 기자가 문을 잠그고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Some people are resting on the steps.','몇몇 사람들이 계단에서 쉬고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A woman is stepping down from a train.','여자가 기차에서 내리고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A food vendor is walking up the stands.','음식 파는 사람이 관중석 위로 걸어 올라가고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are standing in line at a ticket counter.','사람들이 매표소 앞에 줄을 서 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The man is turning the pages of a book.','남자가 책의 페이지를 넘기고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is paging through her notebook.','여자가 공책 페이지를 넘겨보고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are watching a slide show.','사람들이 슬라이스 쇼를 보고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is sliding down a hill.','남자가 언덕에서 미끄러져 내려오고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The lights in the room have been turned off.','방 안의 전등이 꺼져 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The family is lighting the candles.','가족이 초에 불을 붙이고 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is responsible for sending the invitations?','초대장 발송은 누가 담당하나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Are there any tickets available for today\'s show?','오늘 공연 입장권이 있습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('When will she be available for consultations?','언제 그 여자와 상담할 수 있습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Our utility bill is a lot higher this month, isn\'t it?','우리 공과금이 이번 달에 훨씬 더 많이 나왔어요, 그렇죠?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is going to repair the computer system?','누가 컴퓨터 시스템을 수리하나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Why don\'t we offer a vegetarian dish at the lunch?','점심 때 채식 요리를 제공하는 게 어떤가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Didn\'t he accept the job offet?','그 남자가 일자리 제안을 수락하지 않았나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('What is the status of this bill?','이 청구서는 어떤 상태인가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How often should the shipping records be updated?','배송 기록은 얼마나 자주 업데이트 되야 하나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Our advertisement is being recorded in Studio B.','저희 광고는 B 스튜디오에서 녹화되고 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The sightseeing bus leaves from over there.','관광버스는 저쪽에서 출발합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Where did you leave your umbrella?','우산을 어디에 두었습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Do you know who will be leading the training session today?','누가 오늘 교육 세션을 이끄는지 아시나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Didn\'t you organize the emplyee picnic last year?','당신이 작년에 회사 야유회를 준비하지 않았나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is working on revising the report?','누가 보고서를 수정하고 있나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Why don\'t you join us for dinner tonight?','오늘 밤에 식사를 같이 하는게 어때요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('When did you join the company?','언제 입사하셨어요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Can I borrow your calculator, or are you using it now?','계산기 좀 빌려도 될까요, 아니면 지금 쓰고 계신가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The hotel charges cancellation fees.','그 호텔은 취소 수수료를 부과합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am going to charge the battery.','배터리를 충전하려고 합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is the person in charge of payroll?','급여 담당자는 누구입니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have a job interview with the local newspaper.','지역 신문사와 면접이 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are stored on the bottom shelf.','그것들은 맨 아래 선반에 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Would you prefer a table outdoors or indoors?','실외 테이블이 좋으세요, 실내 테이블이 좋으세요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who approved the budget estimate?','누가 예산액을 승인했습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Where will you be sending this document?','이 문서를 어디로 보낼 건가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Are you ready to order, or do you need more time?','주문하시겠어요, 아니면 시간이 더 필요하세요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Could I look at the financial projections for next year?','내년도 재무 예상안을 볼 수 있을까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Shall I contact you by e-mail or by phone?','제가 이메일로 연락할까요, 아니면 전화로 연락할까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('You paid all the bills, didn\'t you?','청구서를 다 지불했죠, 그렇죠?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Would you like to pay now, or be billed later?','지금 결제하시겠습니까, 아니면 나중에 청구 받으시겠습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is going to meet our colleagues at the airport?','누가 공항에 동료들을 마중나갈 건가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('My performance review went very well.','제 인사고과는 매우 좋았어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We have hired a consultant to review it.','우리는 검토를 위해 컨설턴트를 고용했습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How much do these sweaters cost?','이 스웨터들은 얼마입니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Did he make it there in time?','그는 제시간에 거기에 갔습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Could you proofread the translation before we send it to the Madrid office?','마드리드 사무소로 보내기 전에 번역을 교정해 주시겠습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How did the committee select the finalists for the prize?','위원회는 어떻게 수상 최종 후보자들을 선정했나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Our manager will be retiring in July.','우리 관리자는 7월에 퇴직합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('When was the sculpture gallery added to the museum?','언제 저 조각상이 박물관에 추가되었나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Why don\'t I hang up these flyers for you?','이 전단지들은 제가 대신 걸어드릴까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How can we meet the project deadline?','프로젝트 마감일을 어떻게 마출 수 있습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How long will it take to ship this item?','이 물건을 배송하는데 시간이 얼마나 걸립니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('When does the shipment of running shoes arrive?','운동화 배송이 언제 도착합니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Did you hear who is going to take over the manager\'s position?','누가 관리자 자리를 인계받는지 들었습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How long does it take for you to get to work?','회사 가는데 얼마나 걸리세요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Please return these books to the library by June 2nd.','이 책들을 6월 2일까지 도서관에 반납하세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('When will he be returning from his vacation?','그는 언제 휴가에서 복귀할 예정입니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Should I submit my first draft, or only the final version?','초안을 제출해야 할까요, 아니면 최종본만 제출하면 될까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It depends on the nature of the problem.','그것은 문제의 본질에 달려 있다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Why has the book\'s release date been delayed?','그 책의 출간일자는 왜 미뤄졌나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Could you order these supplies today?','오늘 이 비품들을 주문해 주시겠어요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Where should I submit my registration form?','신청서를 어디에 제출해야 할까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The contract negotiations took longer than I expected.','계약 협상이 제가 예상했던 것보다 오래 걸렸어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Would you mind changing seats with me?','저와 자리를 바꿔 주시겠습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How did you find out about him leaving?','그가 떠나는 것을 어떻게 알았어요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Would you like one or two copies of the financing agreement?','융자동의서 사본을 한두 부 드릴까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Is the employee appreciation dinner going to be formal or informal?','직원 감사 만찬은 격식을 차린 자리인가요? 아니면 편안한 자리인가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How many people are coming to the awards banquet?','시상식 연회에 몇 명이나 오나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('What was the presentation about?','그 발표는 무엇에 관한 것이었나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She canceled our newpaper subscription, didn\'t she?','그녀가 우리 신문 구독을 취소했죠, 그렇죠?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('A parade was scheduled to go through town.','행렬은 마을을 통과할 예정이었습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will have to check the schedule.','일정을 확인해 봐야겠습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I processed his froms this morning.','제가 오늘 아침에 그의 서류를 처리했어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How many people are coming to the reception tonight?','오늘밤 환영회에 몇 명이 오나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We may want to consult some experts.','우리는 아마 전문가들에게 조언을 구해야 할 것 같아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('When will I be reimbursed for my travel expenses?','출장 경비는 언제 환급받습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('This is the most challenging job I have ever had.','이 일은 제가 지금까지 해본 것 중에 가장 힘든 일이예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We are going to run out of paper soon.','곧 종이가 다 떨어질 거예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is transferring to a new office.','그녀는 새 지사로 전근 갑니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is responsible for filing the invoices?','누가 청구서를 철하는 것을 담당하나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How should we celebrate his retirement?','그의 은퇴를 어떻게 축하해향 할까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Are you riding your bike to work today?','오늘 회사에 자전거 타고 가세요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Could you give me a ride to work tomorrow?','내일 회사에 저를 좀 태워주실 수 있나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Are you going to label those file folders or should I?','저 서류철에 라벨을 붙이실 건가요, 아니면 제가 할까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Where can I get some shipping labels?','어디서 배송 라벨을 구할 수 있나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is the new supervisor at the factory?','누가 공장의 새로운 감독관인가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Please read this manual before tomorrow\'s training session.','내일 교육 시간 전에 이 설명서를 읽으세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('You should sign at the bottom.','맨 아래에 서명해야 합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('What does the sign say?','안내판에 뭐라고 쓰여 있나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is going to lead the tour?','누가 투어를 이끌 예정입니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Which road leads to the park headquarters?','어떤 길이 공원 관리사무소로 이어지나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who monitors the factory\'s safety standards?','누가 공장의 안전 기준을 감독하나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Isn\'t this the monitor that breaks down every week?','이건 매주 고장나는 그 모니터 아닌가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('You have not taken inventory yet, have you?','재고 조사를 아직 하지 않았죠, 그렇죠?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Maybe you need to show identification.','어쩌면 신분증을 제시해야 합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Why don\'t you wait to see the survey results before making a decision?','결정하기 전에 설문조사 결과를 기다려 보는게 어떤가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Have changes been suggested for the engine design?','엔진 디자인에 수정 사항이 제안되었나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('You should go ahead and do that.','어서 그렇게 하세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who does this reference manual belong to?','이 참조 설명서는 누구의 것인가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Please make sure to enter your hours on this form.','이 양식에 당신의 근무 시간을 꼭 입력하세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Where can I donate some old office equipment?','오래된 사무 장비를 어디에서 기부할 수 있나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The price was just lowered.','가격이 막 인하되었습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Why is she transferring to the new branch?','왜 그녀가 새 지점으로 전근가나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is managing the production line?','누가 생산 라인을 관리하나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('How did he manage to pay for the trip?','그가 어떻게 여행 경비를 마련할 수 있었나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Let\'s call the stockroom and ask for more supplies.','비품실에 전화해서 물품을 더 요청합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Will he pick up his order, or should we deliver it?','그가 직접 주문한 물건을 찾아가나요, 아니면 배달해 드려야 하나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Could you recommend any good restaurants in the area?','지역에 괜찮은 음식점을 추천해 주시겠습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The tools were purchased at a discount.','연장들은 할인 가격으로 구입했습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Please put the receipt in the bag with my purchase.','영수증을 구매한 물품과 함께 가방에 넣어 주십시오.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I was just about to head home.','막 집으로 가려던 참이었어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who is the head of the Human Resources Department?','인사부의 부서장은 누구입니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Let me know if your are free to talk today.','오늘 이야기할 시간이 있는지 내게 알려 주세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Could you lend me the training video?','교육 비디오 좀 빌려주시겠어요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Please weight your bag carefully.','가방 무게를 잘 재어 주십시오.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('You accept submissions from freelance writers, don\'t you?','당신이 프리랜서 작가들의 원고를 받죠, 그렇죠?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The food in the cafeteria has improved a lot this year, hasn\'t it?','구내식당 음식이 올해 많이 나아졌어요, 그렇죠?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I know a great place downtown.','시내에 멋진 장소를 알고 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('What else is required to complete the loan agreement?','대출 계약서를 작성하는 데 그 밖에 어떤 것이 더 필요한가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Is it possible to renew my fishing license over the phone?','전화로 낚시 면허증 갱신이 가능할까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Aren\'t you traveling to China at the end of this month?','당신 이 달 말에 중국으로 여행 가지 않나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('No later than seven o\'clock.','늦어도 7시까지입니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Seven o\'clock at the latest.','늦어도 7시까지입니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We have added a lot of new employees lately.','최근에 신입 직원을 많이 채용했습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Aren\'t you supposed to be on holiday this week?','이번 주에 휴가 가기로 한거 아니었어요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Would you like to join the local health club?','지역 헬스클럽에 가입하시겠습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She deserves the recognition.','그녀는 인정받을 만합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Can I help you bring those boxes upstairs?','위층으로 상자 옮기는 일 도와드릴까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I wonder who will be hired as an assistant manager, don\'t you?','부팀장으로 누가 채용될지 궁금하네요, 그렇죠?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('There is some mail for you.','당신에게 우편물이 와 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I\'ll mail it in the morning.','아침에 우편으로 부칠 거에요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Aren\'t we supposed to have a meeting this afternoon?','우리 오늘 오후에 회의 하기로 한거 아닌가요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I don\'t know anything about it.','그것에 대해서는 전혀 몰라요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Who knows?','누가 알겠어요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have no idea.','몰라요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am not sure.','잘 모르겠어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am not certain.','잘 모르겠어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Nobody knows.','아무도 모르죠.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I wish I knew.','저도 알았으면 좋겠어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Not that I know of.','제가 알기로는 아니에요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have not heard about it.','그것에 대해 들은바가 없어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('No one told me about that.','아무도 그것에 대해 이야기해 주지 않았어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have not been informed.','통지를 받지 못했어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have not been notified.','통지를 받지 못했어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have not been told yet.','아직 들은 바가 없어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('That is news to me.','처음 듣는 이야기예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It is still up in the air.','아직 결정 난게 아니예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am still waiting.','여전히 기다리고 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It has not been discussed yet.','아직 논의되지 않았어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am still thinking about it.','아직 그것에 대해 생각 중이예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have not made up my mind.','아직 결정하지 못했어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am still considering it.','아직 고려 중이예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The manager is reviewing it.','매니저가 검토 중이예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It depends on when it is.','그 때가 언제인지에 달려 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('They are still deciding it.','그들은 아직 결정 중이에요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I haven not checked.','확인해 보지 않았어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will find out.','제가 알아볼게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Let me ask someone.','다른 사람에게 물어볼게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Let me call the supplier.','납품업체에 전화해 볼게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will let you know soon.','곧 알려 드릴게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Let me check that for you.','제가 확인해 볼게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We will see soon.','곧 알게 될 거예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I forgot to bring it.','가져오는 것을 깜빡했어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It completely slipped my mind.','까맣게 잊고 있었어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Refer to your manual.','설명서를 참고해 주세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Visit our Web site for details.','자세한 사항은 웹사이트를 방문해 주세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Go to the reception desk.','접수처로 가 보세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He knows beeter than I do.','그가 저보다 더 잘 알아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('That information is in the e-mail.','그 정보는 이메일에 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Try asking him.','저 남자에게 문의해 보세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Not at all.','전혀요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('If you are not too busy.','당신이 많이 바쁘지 않다면요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('By all means.','그렇게 하세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Suit yourself.','좋을 대로 하세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Yes, I think we had better.','네, 그게 낫겠어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('If it\'s not too much trouble.','그게 너무 수고스럽지 않다면요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('OK, I will be sure to do that.','네, 꼭 그렇게 할게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Thanks, I would like that.','고마워요, 그렇게 하고 싶어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('If you don\'t mind.','괜찮으시다면요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have never considered that.','그것은 전혀 고려해 본 적이 없어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I had rather not.','하지 않는게 낫겠어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I can manage, thanks.','혼자 할 수 있어요, 고마워요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I can handle it, thanks.','혼자 할 수 있어요, 고마워요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Sorry, I have an appointment then.','미안하지만, 그 때 약속이 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I\'m almost done, thanks.','고맙지만, 거의 다 했어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Thanks, but I have other plans.','고맙지만, 다른 계획이 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Let me think about it.','생각해 볼게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am afraid I can\'t.','그럴 수 없어서 유감이에요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am afraid not.','그럴 수 없어요 유감이에요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I wish I could, but I am very busy.','그러고 싶지만 너무 바빠요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I prefer green.','초록색이 더 좋아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will go with the red one.','붉은 것으로 할게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I like the grey ones better.','회색이 더 좋아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Let\'s do the letter first.','편지를 먼저 합시다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I don\'t mind driving.','운전해도 상관 없어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Now would be fine.','지금이 좋겠어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Monday is best for me.','월요일이 저한테는 제일 좋아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The soup sounds good.','수프가 좋을 것 같아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I do not care.','상관없어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It does not matter to me.','저는 상관없어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Whatever your prefer.','원하시는 대로요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Anywhere is fine.','어디라도 좋아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will leave it to you.','당신이 결정해요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It is up to you.','당신이 결정해요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I do not have a preference.','선호하는 게 없어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Either is fine.','어느 쪽이든 괜찮아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Either one is fine with me.','저는 어느 쪽이든 괜찮아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Whichever costs less.','어떤 것이든 더 저렴한 것으로요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It does not make any difference.','별로 차이가 없어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Both of them would be fine.','둘 다 좋을 것 같아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I like both.','둘 다 좋아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I like all of them.','둘다 좋아요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I do not like either of them.','둘 다 아니에요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('None of them.','모두 싫어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I prefer neither.','모두 싫어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Neither, thanks.','모두 싫어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I like neither of them.','모두 싫어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('He is the best candidate for a job.','그가 가장 적합한 구직자예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I do not know which option is best for my company.','어느 선택 사항이 우리 회사에 가장 좋은지 모르겠어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am planning to replace my dishwasher in the near future.','저는 조간만 식기세척기를 교체할 계획이예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The award dinner is not until next month.','시상식 만찬은 다음 달은 되어야 해요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We are in the process of issuing refunds.','환불 절차를 진행하고 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Take a look at the layout for the next issue of our cooking magazine.','저희 요리 잡지의 다음 호 지면 배치를 한번 봐 주세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have called this meeting to discuss the issue.','그 문제를 논의하기 위해 이 회의를 소집했습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is arranging a party to celebrate his promotion.','그녀는 그의 승진을 축하하기 위해 파티를 준비하고 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We would like to let you know about our special promotion.','특별 판촉 행사에 대해 알려 드리고 싶습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will see if he can work an extra shift.','그가 추가 근무를 할 수 있는지 알아볼게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We can shift some of the test work into Lab 1.','테스트 업무의 일부를 1번 실험실로 옮길 수 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('What type of job opening are the speakers discussing?','화자들은 어떤 일자리 공석에 대해 이야기하고 있나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Our office\'s grand-opening celebration is on Monday.','우리 사무실 개점 축하 행사는 월요일에 있습니다');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The executive officers were impressed with everyone\'s work.','간부들은 모든 사람들이 한 일에 대해 감명을 받았습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I would like to start brainstorming about our next perfume.','우리의 다음 향수에 대한 아이디어를 생각해 봤으면 합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I would really appreciate your feedback.','의견을 주시면 정말 감사하겠습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am calling to confirm my room reservation for October 20th.','저희 10월 20일 객실 예약을 확인하려고 전화했습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We handle our own domestic deliveries.','저희는 자사의 국내 배송을 처리합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It came with a one-year warranty.','1년 품질 보증서가 포함되어 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Do you think our budget can cover the additional expense?','우리 예산이 추가 경비를 충당할 수 있을까요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I would like you to cover the mayor\'s press conference on Thursday.','목요일에 사장님의 기자 회견을 취재해 주셨으면 합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Unfortunately, our warranty only covers defective parts.','안타깝게도, 우리 보험은 결함 있는 부품들에 한해서만 보장해 드립니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have just finished reviewing the financial report for the upcoming meeting.','곧 있을 회의를 위해 재정 보고서 검토를 방금 마쳤습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Did he figure out what is wrong with my car?','그가 제 차의 문제점을 알아냈습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It may cost a lot to install a digital projector.','디지털 프로젝터를 설치하는 데 돈이 많이 들지도 모릅니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The factory will bring jobs to our community.','그 공장은 우리 지역 사회에 일자리를 만들어 줄 것입니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('What do I need to do to nominate someone?','제가 누군가를 추천하려면 어떻게 해야 하나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I wanted to ask about one of the novels we are publishing in October.','저희가 10월에 출판하는 소설 중 한 권에 대해 질문하고 싶었습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('This brochure shows what is located on each floor.','이 브로셔를 보면 각 층에 무엇이 있는지 알 수 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She can not locate a product.','그녀는 물건을 찾을 수 없습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I suppose we could hire a contractor to help with the work.','그 일을 도와줄 하청 업체를 고용할 수 있을 거예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We could save money by changing shipping companies.','배송 회사를 바꾸면 돈을 절약할 수 있을 거예요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Please save a copy for our files.','파일 사본을 저장하십시오.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('When I tried to log on to my computer, my password was rejected.','제 컴퓨터에 로그인하려고 할 때 패스워드가 거부되었어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I would like to check out these books and journals.','이 책과 잡지를 대출하고 싶습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('For more information, check out our full-page newspaper ad.','더 자세한 사항은 신문 전면 광고를 확인하세요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It took me an extra 30 minutes to get to work today.','오늘 제가 출근하는데 30분이 더 걸렸어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('If you make a last-minute change, you will not be charged extra.','막판에 변경할 때 추가 비용이 청구되지 않습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will be giving a presentation on maintaining good relationships.','우호적 관계 유지에 관한 프레젠테이션을 할 거에요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I apologize for the inconvenience.','불편을 드려 죄송합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We will arrange a our of the assembly line.','조립 라인 견학을 마련할 예정입니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Have you already made a reservation?','이미 예약을 하셨습니까?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will be sure to stop by her office before I leave.','떠나기 전에 그녀의 사무실에 꼭 들를게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I ordered assorted sandwiches, beverages, and cookies for dessert.','디저트로 갖가지 샌드위치, 음료, 쿠키를 주문했어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have experience as a lifeguard.','저는 구조대원으로 일한 경험이 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Your might find that you experience some drowsiness.','졸음이 올 수 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We are ready to build a larger facility and increase production.','저희는 시설을 확충하고 생산을 늘릴 준비가 되어 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Has he submitted his loan application yet?','그가 대출신청서를 제출했나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I can show you some interesting spots to take visitors.','관광객을 끌 흥미로운 장소들을 안내해 드릴 수 있습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('The recipes we use in our kitchen are fine.','우리 주방에서 사용하는 조리법은 훌륭합니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I will stop by later to show you how to use the time entry system.','제가 나중에 들러서 시간 기입 시스템 사용법을 보여 드릴게요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('My doctor sent a prescription to this pharmacy about an hour ago.','제 담당의가 한 시간쯤 전에 이 약국으로 처방전을 보냈습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am putting together a lunch outing for my department.','우리 부서를 위해 점심 회식을 준비하고 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('It is a brand-new building with a spacious reception area.','그 곳은 로비가 넓은 새 건물입니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am doing a presentation on Wednesday for a potential client.','저는 수요일에 잠재 고객을 위한 발표를 할 예정입니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have definitely noticed an improvement over the past few weeks.','지난 몇 주에 걸쳐 확실히 나아졌다는 걸 느꼈어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I have some work I can finish up in the meantime.','저는 그 동안에 끝낼 수 있는 일이 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('We will be moving our store when our lease is up.','우리는 임대 계약이 끝나면 가게를 옮길 예정입니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I am considering doing some remodeling that might increase its value.','그것의 가치를 높일 수 있도록 리모델링을 고려하고 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('Did they raise their prices again?','그들이 가격을 또 올렸나요?');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('She is on the telephone with an overseas customer.','그녀는 해외 고객과 통화를 하고 있어요.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('I hear you will be working overseas.','당신이 해외에서 근무하게 될 거라고 들었습니다.');
INSERT INTO `Sentence` (`englishSentence`,`koreanSentence`) VALUES ('You can set up a payment account on our Web site.','저희 웹사이트에서 지불 계좌를 개설할 수 있습니다.');
